name: Omnibenchmark runner
author: Izaskun Mallona
description: Runs omnibenchmarks with miniforge backends

inputs:
  omnibenchmark_yaml:
    description: path to the omnibenchmark yaml
    required: true
    default: 'tests/Clustering.yaml'
outputs:
  time: # id of output
    description: 'Benchmarking timestamp.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    YAML: ${{ inputs.omnibenchmark_yaml }}
