name: Run omnibenchmark via a github action
author: Izaskun Mallona izaskun.mallona@gmail.com
description: Runs omnibenchmarks

inputs:
  yaml:
    description: path to the omnibenchmark yaml
    required: true
  backend:
    description: software backend to use (conda or apptainer)
    required: true
    default: conda
  cores:
    description: number of concurrent jobs
    required: false
    default: 1
runs:
  using: "composite"
  steps:
    - name: Set vars for global use
      id: vars
      shell: bash
      run: |
        echo "YAML=${{ inputs.yaml }}" >> "${GITHUB_OUTPUT}"
        echo "BACKEND=${{ inputs.backend }}" >> "${GITHUB_OUTPUT}"
        echo "CORES=${{ inputs.cores }}" >> "${GITHUB_OUTPUT}"
        
    - name: Check out repository
      uses: actions/checkout@v4
      
    - uses: eWaterCycle/setup-apptainer@v2
      if: inputs.backend == 'apptainer'
      with:
        apptainer-version: 1.4.0

    - name: Install ob (with) micromamba
      uses: mamba-org/setup-micromamba@v2
      if: inputs.backend == 'apptainer' || inputs.backend == 'conda'
      with:
        environment-file: env/omnibenchmark_conda.yaml
        cache-environment: true
        create-args: >-
          python=3.12
          pip
          conda
        post-cleanup: environment # all

    - name: Install omnibenchmark (main)
      shell: bash -l {0}
      run: |
        pip install git+https://github.com/omnibenchmark/omnibenchmark.git

    - name: Run benchmark
      env:
        YAML: ${{ steps.vars.outputs.YAML }}
        BACKEND: ${{ steps.vars.outputs.BACKEND }}
        CORES: ${{ steps.vars.outputs.CORES }}        
      shell: bash -l {0}
      run: |
        ob run benchmark -b "$YAML" --local --cores "$CORES" --yes
         
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Benchmarking results
        path: ${{ github.workspace }}/out
