name: Run omnibenchmark via a github action
author: Izaskun Mallona izaskun.mallona@gmail.com
description: Runs omnibenchmarks

inputs:
  yaml:
    description: path to the omnibenchmark yaml
    required: true
  backend:
    description: software backend to use (miniforge, micromamba, apptainer)
    required: true
outputs:
  time: # id of output
    description: 'Benchmarking timestamp.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    YAML: ${{ inputs.yaml }}
    BACKEND: ${{ inputs.backend }}
