name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        uses: imallona/run_omnibenchmark_miniforge@main
        with:
          yaml: tests/Clustering.yaml
          backend: miniforge
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmarking results
          path: ${{ github.workspace }}/output
