name: test_conda

on: [push]

jobs:
  plain_conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        uses: imallona/run_omnibenchmark
        with:
          yaml: tests/Clustering.yaml
          backend: conda
          cores: 1

