name: test_apptainer

on: [push]

jobs:
  plain_conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        uses: imallona/run_omnibenchmark@main
        with:
          yaml: tests/Clustering_apptainer.yaml
          backend: apptainer
          cores: 1

